server:
  port: 8775
eureka:
#  instance:
#    hostname: ${spring.application.name}
#    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client

eureka-client-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.myself.config.LoadBalanced

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 500
  ConnectTimeout: 500
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300