eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8780
spring:
  application:
    name: yd-zuul
zuul:
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000
  sensitive-headers:
#zuul:
#  routes:
#    api-a:
#      path: /api-a/**
#      serviceId: spring-cloud-test1

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000