server:
  port: 8761
eureka:
  instance:
    hostname: standalone
#    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    instance-id: ${spring.application.name}
#    instance-id: 1
  client:
    register-with-eureka: false #表明该服务不会像eureka注册自己的信息
    fetch-registry: false #表明该服务不会像eurekaserver获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-service
